### ISSUE TITLE
Installation fails - no 'pp' command

### ISSUE THREAD

**Issue by karlsackett** [paulroub/todo.txt-recurring-tasks#1]
Running the Makefile on my Debian Linux workstation produces this output:

``` bash
miranda$ make
pp -o recur -P --lib=lib todo-recur.pl
make: pp: Command not found
make: *** [recur] Error 127
```

**Comment by paulroub** [comment]
What? You don't have every non-standard Perl extension that I have installed?

Sorry, you'll want to install the PAR::Packer module from cpan.  `sudo cpan PAR::Packer` should do the trick.

Leaving this open until (a) this works for you and (b) I add that requirement to the README.

**Comment by karlsackett** [comment]
Problem solved. I installed the libpar-packer-perl package and everything else worked. Thanks for your help.
